# Generated by Django 2.2.3 on 2019-07-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('timestamp', models.DateTimeField(verbose_name='编辑时间')),
            ],
            options={
                'db_table': 'blog_post',
            },
        ),
    ]
